# Site settings
title: Iteration makes perfect 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing my learnings, readings and stories. Thank you. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _yulun_
github_username:  jekyll

# Build settings
markdown: kramdown
